
# ==============================================================================

# Run 01_Data_cleaning/02_make_yearly_SPEI.R first to generate the spei_long dataframe

# This script visualises population-weighted SPEI12 trends for each Indian state
# over time using the spei_long dataframe generated by yearly_SPEI.R. It filters
# the data, excludes missing and disputed observations, and creates faceted state
# trend plots split into two groups for clearer visualisation.

# ==============================================================================

library(sf)
library(rnaturalearth)
library(rnaturalearthdata)
library(dplyr)
library(ggplot2)
library(patchwork)
library(grepl)

# ============================================================
# 0. Some overview SPEI grpahs
# ============================================================

# Filter for weighted data and remove NA/Disputed rows
plot_data <- spei_long %>%
  filter(type == "weighted") %>%
  filter(!is.na(spei12)) %>%
  filter(!grepl("DISPUTED", state_name))

# Split states into two groups for two separate grids
all_states <- sort(unique(plot_data$state_name))
midpoint <- ceiling(length(all_states) / 2)
states_group1 <- all_states[1:midpoint]
states_group2 <- all_states[(midpoint + 1):length(all_states)]

create_state_grid <- function(data_subset, title_suffix) {
  ggplot(data_subset, aes(x = year, y = spei12)) +
    # Add a horizontal line at 0 for reference
    geom_hline(yintercept = 0, color = "gray50", linetype = "dashed") +    # The main line and points
    geom_line(color = "steelblue", size = 1) +
    geom_point(aes(color = spei12 > 0), size = 1.5) +
    # Formatting the "Grid"
    facet_wrap(~state_name, ncol = 4, scales = "free_y") + 
    # Styling
    scale_color_manual(values = c("TRUE" = "blue", "FALSE" = "red"), guide = "none") +
    scale_x_continuous(labels = scales::label_number(accuracy = 1, big.mark = "")) +
    scale_y_continuous(labels = scales::label_number(accuracy = 1))+
    theme_minimal() +
    labs(
      title = paste("Population-Weighted SPEI12 Trends:", title_suffix),
      subtitle = "Red points indicate drought conditions (SPEI < 0)",
      x = "Year",
      y = "Weighted SPEI12"
    ) +
    theme(
      strip.text = element_text(face = "bold", size = 8),
      axis.text = element_text(size = 7)
    )
}

grid0 <- create_state_grid(plot_data, "Raw data")
print(grid0)

# Generate Group 1 (A-M roughly)
grid1 <- create_state_grid(plot_data %>% filter(state_name %in% states_group1), "Group A")
print(grid1)

# Generate Group 2 (N-Z roughly)
grid2 <- create_state_grid(plot_data %>% filter(state_name %in% states_group2), "Group B")
print(grid2)

india <- st_read("~/Desktop/MSC THESIS/Data works/Code/Data/geography/State_District_Sub-district_Boundary_of_entire_India/State Boundary.shp")

spei_weighted_long <- spei_yearly %>%
  pivot_longer(
    cols = starts_with("weighted_SPEI12_"),
    names_to = "year",
    names_prefix = "weighted_SPEI12_",
    values_to = "spei12"
  ) %>%
  mutate(year = as.integer(year), type = "Weighted") |> 
  filter(!grepl("disputed", STATE, ignore.case = TRUE))

spei_unweighted_long <- spei_yearly %>%
  pivot_longer(
    cols = starts_with("unweighted_SPEI12_"),
    names_to = "year",
    names_prefix = "unweighted_SPEI12_",
    values_to = "spei12"
  ) %>%
  mutate(year = as.integer(year), type = "Unweighted") |> 
  filter(!grepl("disputed", STATE, ignore.case = TRUE))

spei_combined <- bind_rows(spei_weighted_long, spei_unweighted_long)

boxplot_comparison_spei <- ggplot(spei_combined, 
                                  aes(x = reorder(STATE, spei12, FUN = median), 
                                      y = spei12, 
                                      fill = type)) +
  geom_boxplot(outlier.size = 0.8, alpha = 0.7) +
  scale_fill_manual(values = c("Weighted" = "steelblue", 
                               "Unweighted" = "tomato")) +
  coord_flip() +
  labs(
    title = "State-Level Distribution of SPEI12: Weighted vs Unweighted",
    x = NULL, y = "SPEI12",
    fill = NULL
  ) +
  theme_minimal() +
  theme(legend.position = "top")

boxplot_comparison_spei

# ============================================================
# 1. SPEI — Summary Statistics
# ============================================================

# --- 1a. State-level summary (mean, sd, min, max across years) ---
spei_state_summary <- spei_weighted_long %>%
  group_by(STATE) %>%
  summarise(
    mean_spei  = mean(spei12, na.rm = TRUE),
    sd_spei    = sd(spei12, na.rm = TRUE),
    min_spei   = min(spei12, na.rm = TRUE),
    max_spei   = max(spei12, na.rm = TRUE),
    range_spei = max_spei - min_spei,
    .groups = "drop"
  ) %>%
  arrange(desc(sd_spei))   # states with most inter-year variation first

print(spei_state_summary)

spei_summary <- spei_weighted_long %>%
  summarise(
    mean_inf  = mean(spei12, na.rm = TRUE),
    median_inf = median(spei12, na.rm = TRUE),
    sd_inf    = sd(spei12, na.rm = TRUE),
    min_inf   = min(spei12, na.rm = TRUE),
    max_inf   = max(spei12, na.rm = TRUE),
    count_inf   = n()
  )

print(spei_summary)

# --- 1b. Ranked: which states have highest inter-year variation? ---
spei_variation_rank <- spei_state_summary %>%
  dplyr::select(STATE, sd_spei, range_spei) %>%
  mutate(rank_sd = rank(-sd_spei))

print(spei_variation_rank)

# ============================================================
# 1. SPEI — Plots
# ============================================================

# --- Plot A: SD by state (inter-year variation ranking) ---
ggplot(spei_state_summary, aes(x = reorder(STATE, sd_spei), y = sd_spei)) +
  geom_col(fill = "steelblue") +
  coord_flip() +
  labs(
    title = "Inter-Year Variation in SPEI12 by State",
    x = NULL, y = "SD of SPEI12 across years"
  ) +
  theme_minimal()

# # --- Plot B: Distribution of SPEI12 per state (boxplot) ---
# ggplot(spei_long_stats, aes(x = reorder(STATE, spei12, FUN = median), y = spei12)) +
#   geom_boxplot(fill = "lightblue", outlier.size = 1) +
#   coord_flip() +
#   labs(
#     title = "State-Level Distribution of SPEI12, weighted",
#     x = NULL, y = "SPEI12"
#   ) +
#   theme_minimal()

# --- Plot C: Heatmap — SPEI12 by state × year ---
ggplot(spei_weighted_long, aes(x = year, y = reorder(STATE, spei12, FUN = mean), fill = spei12)) +
  geom_tile() +
  scale_fill_gradient2(low = "brown", mid = "white", high = "darkblue", midpoint = 0) +
  labs(
    title = "SPEI12 by State and Year",
    x = "Year", y = NULL, fill = "SPEI12"
  ) +
  theme_minimal()

# Physical map

india_map_data <- india %>%
  left_join(
    spei_state_summary %>% 
      dplyr::select(STATE, mean_spei, sd_spei) %>%
      left_join(spei_variation_rank %>% dplyr::select(STATE, rank_sd), by = "STATE"),
    by = c("STATE" = "STATE")
  ) |>  filter(!grepl("disputed", STATE, ignore.case = TRUE))

unmatched <- india_map_data %>% 
  filter(is.na(sd_spei)) %>% 
  pull(STATE)
print(unmatched)

# mean spei
map_mean <- ggplot(india_map_data) +
  geom_sf(aes(fill = mean_spei), color = "white", linewidth = 0.3) +
  geom_sf_text(aes(label = STATE), size = 2, color = "black") + # state names
  scale_fill_gradient2(
    low      = "brown",       # dry / negative SPEI
    mid      = "lightyellow",
    high     = "darkblue",    # wet / positive SPEI
    midpoint = 0,
    na.value = "grey80",
    name     = "Mean SPEI12"
  ) +
  labs(
    title    = "Average SPEI12 by State",
    subtitle = "Brown = drier, Blue = wetter on average"
  ) +
  theme_void() +
  theme(
    plot.title    = element_text(face = "bold", size = 13),
    plot.subtitle = element_text(size = 9),
    legend.position = "right"
  )
map_mean

# spei variation
map_variation <- ggplot(india_map_data) +
  geom_sf(aes(fill = sd_spei), color = "white", linewidth = 0.3) +
  scale_fill_gradient(
    low  = "lightyellow",
    high = "darkblue",
    na.value = "grey80",        # unmatched states show as grey
    name = "SD of SPEI12"
  ) +
  labs(
    title    = "Inter-Year Variation in SPEI12 by Indian State",
    subtitle = "Darker = higher year-to-year variability in drought index",
    caption  = "Source: spei_variation_rank"
  ) +
  theme_void() +
  theme(
    plot.title    = element_text(face = "bold", size = 14),
    plot.subtitle = element_text(size = 10),
    legend.position = "right"
  )


# SPEI over time

# ============================================================
# SPEI12 over time — one line per state
# ============================================================

ggplot(spei_weighted_long, aes(x = year, y = spei12, group = STATE, color = STATE)) +
  geom_line(linewidth = 0.6, alpha = 0.7) +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey40") +
  scale_x_continuous(breaks = scales::pretty_breaks()) +
  labs(
    title    = "SPEI12 over Time by State",
    subtitle = "Dashed line = 0 (neutral); below = drier, above = wetter",
    x        = "Year",
    y        = "SPEI12",
    color    = NULL
  ) +
  theme_minimal() +
  theme(
    legend.position = "right",
    panel.grid.minor = element_blank()
  )

ggplot(spei_weighted_long, aes(x = year, y = spei12, group = STATE)) +
  geom_line(linewidth = 0.5, color = "steelblue") +
  geom_hline(yintercept = 0, linetype = "dashed", color = "grey40") +
  facet_wrap(~ STATE, ncol = 6) +
  scale_x_continuous(
    breaks = seq(
      min(spei_weighted_long$year),
      max(spei_weighted_long$year),
      by = 2
    ),
    expand = c(0, 0)
  ) +
  labs(
    title = "SPEI12 over Time by State",
    x = "Year", y = "SPEI12"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(size = 6, angle = 45, hjust = 1),
    axis.text.y = element_text(size = 6),
    strip.text = element_text(size = 7, face = "bold"),
    panel.grid.minor = element_blank()
  )
